server:
  port: 9006

spring:
  application:
    name: QB-PAYROLL-SERVICE
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
    service.name: QB-PAYROLL-SERVICE
    sender.type: web
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
